# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170816_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.TextField(blank=True, max_length=30, verbose_name='Автор задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата постановки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=50, verbose_name='Задача'),
        ),
    ]
