# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-16 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170816_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(blank=True, max_length=30, verbose_name='Автор задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(verbose_name='Задача'),
        ),
    ]
